### PR TITLE
Pull multi-select from npm

### PR DESCRIPTION
**Pull request by BhamelinD2L**
Switches the multi-select reference from github to instead use the npm registry through https://www.npmjs.com/package/@brightspace-ui-labs/multi-select

### CODE REVIEW

**Review by devpow112 — DISMISSED** [review]

**Comment by devpow112** [comment]
Currently CI is busted due to an issue with the NPM version we are using. Once that's fixed I'll re-run it and merge this.

**Comment by devpow112** [comment]
FYI, @semibran you'll want to pull this into your changes for `master` as well.

**Comment by BhamelinD2L** [comment]
Appreciate you letting me know, thanks!

**Review by devpow112 — APPROVED** [review]

**Comment by BhamelinD2L** [comment]
Sorry for switching the versions around - I was trying to deal with an issue with another repo and wanted things sync'd. Should be fine now.

**Review by devpow112 — APPROVED** [review]

**Pull request merged**
