### PR TITLE
Make scrollbar work

### PR DESCRIPTION
**Pull request by iFun**
This will make the scrollbar in d2l-rubric work.
Screen Shot 2019-03-20 at 16 12 30

Thanks to Chris K and Jeff

### CODE REVIEW

**Comment by omsmith** [comment]
I don't see a scrollbar? Did you want `overflow: auto`?

**Comment by jstefaniuk-d2l** [comment]
Some browsers hide the scrollbar if not in motion

**Comment by ChrisKraljevicD2L** [comment]
There's an existing scrollbar, but some surrounding CSS was preventing it from working. Or are ya talking about in the screenshot? Because this CSS is what worked for Jeff and I testing this out.

**Comment by iFun** [comment]
> I don't see a scrollbar? Did you want `overflow: auto`?

its there. once you scroll inside the list.

**Pull request merged**
