### PR TITLE
change repo name to match github path

### PR DESCRIPTION
**Pull request by djwester**

### CODE REVIEW

**Comment by dlockhart** [comment]
You may want to bump the version in here at the same time?

**Comment by dlockhart** [comment]
Although it's already way out of sync with the GitHub release/tags, so meh.

**Comment by svanherk** [comment]
Should we just remove the version to match our other Polymer 3 repos? Will that cause issues?

**Comment by dlockhart** [comment]
Yeah that works too. If this ever needs to get published to NPM we'll need to bring it back then.

**Comment by djwester** [comment]
I'll just remove the version.

**Pull request merged**
